# Generated by Django 3.1.14 on 2021-12-29 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211229_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='file',
            field=models.FileField(upload_to='file/%Y/%m/%d'),
        ),
    ]
