# Generated by Django 3.1.14 on 2021-12-29 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211229_1759'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apps',
            name='a1',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='apps',
            name='content',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='apps',
            name='giturl',
            field=models.URLField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='apps',
            name='link',
            field=models.URLField(max_length=10000),
        ),
    ]
