# Generated by Django 3.1.14 on 2021-12-30 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211230_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.CharField(max_length=1000)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('Apps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.apps')),
            ],
            options={
                'ordering': ('pub_date',),
            },
        ),
    ]
