# Generated by Django 3.1.14 on 2021-12-30 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='Apps',
            new_name='apps',
        ),
    ]
